// Postgres (Supabase) implementation of Storage — the deployed backend.
//
// Two constraints shape this file. First, it must survive serverless: a pool of
// one or two connections, opened lazily, because a Vercel function has no
// long-lived process to share a big pool with. Second, it must run behind
// Supabase's transaction pooler, which forbids server-side prepared statements —
// so every query is a plain parameterised text query, never a named one.

import pg from 'pg';
import { adviseOnConnectionString } from './advice.js';
import type { NoteScope } from '@loadbearing/shared';
import type {
  ApiTokenRow,
  AttemptRow,
  CanvasRow,
  MasteryRow,
  NoteRow,
  ProjectRow,
  ReviewQueueRow,
  StatsAgg,
  Storage,
  UserRow,
} from './types.js';

const MASTERY_ALPHA = 0.3;
const CACHE_TTL_DAYS = 14;

const ATTEMPT_COLS =
  'id, problem_id, round, graph_json, score_json, overall, twist_text, created_at';

interface RawAttempt {
  id: string | number;
  problem_id: string;
  round: string | number;
  graph_json: string;
  score_json: string;
  overall: string | number;
  twist_text: string | null;
  created_at: Date | string;
}

/**
 * The schema, one entry per table, in dependency order. Adding a table here is
 * all that is needed for it to appear on a deployment that already exists.
 */
const SCHEMA: { table: string; create: string; indexes?: string[] }[] = [
  {
    table: 'users',
    create: `CREATE TABLE users (
      id UUID PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      pass_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
  },
  {
    table: 'attempts',
    create: `CREATE TABLE attempts (
      id BIGSERIAL PRIMARY KEY,
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      problem_id TEXT NOT NULL,
      round INTEGER NOT NULL DEFAULT 1,
      graph_json TEXT NOT NULL,
      score_json TEXT NOT NULL,
      overall INTEGER NOT NULL,
      twist_text TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
    indexes: ['CREATE INDEX idx_attempts_user_problem ON attempts(user_id, problem_id)'],
  },
  {
    table: 'mastery',
    create: `CREATE TABLE mastery (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      concept TEXT NOT NULL,
      ema_score DOUBLE PRECISION NOT NULL,
      attempts INTEGER NOT NULL DEFAULT 0,
      last_seen TIMESTAMPTZ,
      PRIMARY KEY (user_id, concept)
    )`,
  },
  {
    table: 'problems_custom',
    create: `CREATE TABLE problems_custom (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      id TEXT NOT NULL,
      json TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (user_id, id)
    )`,
  },
  {
    table: 'settings',
    create: `CREATE TABLE settings (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      key TEXT NOT NULL,
      value TEXT NOT NULL,
      PRIMARY KEY (user_id, key)
    )`,
  },
  {
    table: 'designs',
    create: `CREATE TABLE designs (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      problem_id TEXT NOT NULL,
      graph_json TEXT NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (user_id, problem_id)
    )`,
  },
  {
    table: 'notes',
    create: `CREATE TABLE notes (
      id UUID PRIMARY KEY,
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      scope TEXT NOT NULL,
      scope_id TEXT NOT NULL,
      title TEXT NOT NULL DEFAULT '',
      body TEXT NOT NULL DEFAULT '',
      position INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
    indexes: ['CREATE INDEX notes_by_scope ON notes (user_id, scope, scope_id, position)'],
  },
  {
    table: 'api_tokens',
    // The id is generated by the application rather than the database: it is half of
    // a credential the caller must be handed at creation time, so it cannot be a
    // value the row only reveals after the insert.
    create: `CREATE TABLE api_tokens (
      id TEXT PRIMARY KEY,
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL DEFAULT '',
      hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_used_at TIMESTAMPTZ
    )`,
    indexes: ['CREATE INDEX api_tokens_by_user ON api_tokens (user_id, created_at DESC)'],
  },
  {
    table: 'chats',
    create: `CREATE TABLE chats (
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      problem_id TEXT NOT NULL,
      turns_json TEXT NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      PRIMARY KEY (user_id, problem_id)
    )`,
  },
  {
    table: 'reference_designs',
    create: `CREATE TABLE reference_designs (
      problem_id TEXT PRIMARY KEY,
      graph_json TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
  },
  {
    table: 'llm_cache',
    create: `CREATE TABLE llm_cache (
      key TEXT PRIMARY KEY,
      response TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
  },
  {
    table: 'projects',
    create: `CREATE TABLE projects (
      id UUID PRIMARY KEY,
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      summary TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
    indexes: ['CREATE INDEX idx_projects_user ON projects(user_id, updated_at DESC)'],
  },
  {
    table: 'project_canvases',
    create: `CREATE TABLE project_canvases (
      id UUID PRIMARY KEY,
      project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      note TEXT NOT NULL DEFAULT '',
      graph_json TEXT NOT NULL,
      position INTEGER NOT NULL DEFAULT 0,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`,
    indexes: ['CREATE INDEX idx_canvases_project ON project_canvases(project_id, position)'],
  },
];

const iso = (v: Date | string | null): string =>
  v === null ? '' : v instanceof Date ? v.toISOString() : String(v);

interface RawProject {
  id: string;
  name: string;
  summary: string;
  created_at: Date | string;
  updated_at: Date | string;
  canvas_count?: string | number;
}

interface RawCanvas {
  id: string;
  project_id: string;
  name: string;
  note: string;
  graph_json: string;
  position: string | number;
  updated_at: Date | string;
}

const toProject = (r: RawProject): ProjectRow => ({
  id: r.id,
  name: r.name,
  summary: r.summary,
  createdAt: iso(r.created_at),
  updatedAt: iso(r.updated_at),
});

const toCanvas = (r: RawCanvas): CanvasRow => ({
  id: r.id,
  projectId: r.project_id,
  name: r.name,
  note: r.note,
  graphJson: r.graph_json,
  position: Number(r.position),
  updatedAt: iso(r.updated_at),
});

interface RawNote {
  id: string;
  scope: string;
  scope_id: string;
  title: string;
  body: string;
  position: string | number;
  created_at: Date | string;
  updated_at: Date | string;
}

interface RawApiToken {
  id: string;
  name: string;
  created_at: Date | string;
  last_used_at: Date | string | null;
}

const toApiToken = (r: RawApiToken): ApiTokenRow => ({
  id: r.id,
  name: r.name,
  createdAt: iso(r.created_at),
  lastUsedAt: iso(r.last_used_at),
});

const NOTE_COLS = 'id, scope, scope_id, title, body, position, created_at, updated_at';

const toNote = (r: RawNote): NoteRow => ({
  id: r.id,
  scope: r.scope as NoteScope,
  scopeId: r.scope_id,
  title: r.title,
  body: r.body,
  position: Number(r.position),
  createdAt: iso(r.created_at),
  updatedAt: iso(r.updated_at),
});

const toAttempt = (r: RawAttempt): AttemptRow => ({
  id: Number(r.id),
  problemId: r.problem_id,
  round: Number(r.round),
  graphJson: r.graph_json,
  scoreJson: r.score_json,
  overall: Number(r.overall),
  twistText: r.twist_text,
  createdAt: iso(r.created_at),
});

export class PostgresStorage implements Storage {
  readonly kind = 'postgres';
  private pool: pg.Pool;

  /** Diagnosis of the connection string, surfaced on /api/health. */
  readonly advice: string | null;

  constructor(connectionString: string) {
    // On serverless there is one pool per instance and the platform decides how
    // many instances exist, so the pool must be small: a pool of N multiplies by
    // however many functions happen to be warm. One connection per instance,
    // released quickly, is the shape that survives a pooler's client limit.
    const serverless = Boolean(process.env.VERCEL);
    this.advice = adviseOnConnectionString(connectionString, serverless);
    if (this.advice) console.warn(`[loadbearing] ${this.advice}`);

    this.pool = new pg.Pool({
      connectionString,
      // Supabase terminates TLS with a certificate this client has no root for;
      // the connection is still encrypted, and the host is fixed by the URL.
      ssl: { rejectUnauthorized: false },
      max: Number(process.env.PGPOOL_MAX ?? (serverless ? 1 : 5)),
      idleTimeoutMillis: serverless ? 2_000 : 10_000,
      connectionTimeoutMillis: 15_000,
      // Hand the connection back as soon as the instance goes idle rather than
      // holding a slot open for the next invocation that may never come.
      allowExitOnIdle: serverless,
      // A query that never answers must not become a 60-second gateway timeout:
      // that reports as "the app is broken" with no clue which call stalled.
      // Client-side, so it works behind a pooler that forbids session-level SET.
      query_timeout: 20_000,
    });
  }

  private async q<T = any>(sql: string, params: unknown[] = []): Promise<T[]> {
    const res = await this.pool.query({ text: sql, values: params as any[] });
    return res.rows as T[];
  }

  private async one<T = any>(sql: string, params: unknown[] = []): Promise<T | null> {
    const rows = await this.q<T>(sql, params);
    return rows.length > 0 ? rows[0]! : null;
  }

  /**
   * Creates whatever is missing, and only what is missing.
   *
   * The first version re-ran the whole DDL block on every cold start. CREATE TABLE
   * IF NOT EXISTS still takes an ACCESS EXCLUSIVE lock when it does nothing, so a
   * fleet of functions waking together serialised on catalog locks. The fix for
   * that was to skip everything once `users` existed — which then meant a table
   * added later never appeared on an already-deployed instance.
   *
   * So: one query for the table list, then DDL for the ones that are absent. The
   * steady state is a single SELECT, and a new table still gets created. Note that
   * this handles new TABLES, not changes to existing ones — altering a live column
   * needs a considered migration, not a statement executed by whichever request
   * happens to arrive first.
   */
  async init(): Promise<void> {
    const rows = await this.q<{ table_name: string }>(
      `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`,
    );
    const present = new Set(rows.map((r) => r.table_name));

    for (const step of SCHEMA) {
      if (present.has(step.table)) continue;
      await this.q(step.create);
      for (const index of step.indexes ?? []) await this.q(index);
      console.log(`[loadbearing] created table ${step.table}`);
    }

    await this.pruneCache();
  }

  /** Cached model replies go stale as prompts evolve; two weeks is plenty. */
  private async pruneCache(): Promise<void> {
    await this.q(`DELETE FROM llm_cache WHERE created_at < now() - ($1 || ' days')::interval`, [
      String(CACHE_TTL_DAYS),
    ]);
  }

  async close(): Promise<void> {
    await this.pool.end();
  }

  // ---- users ----

  async createUser(username: string, passHash: string): Promise<UserRow> {
    const row = await this.one<{ id: string; username: string; pass_hash: string; created_at: Date }>(
      `INSERT INTO users (id, username, pass_hash) VALUES (gen_random_uuid(), $1, $2)
       RETURNING id, username, pass_hash, created_at`,
      [username, passHash],
    );
    if (!row) throw new Error('Insert returned no user row');
    return { id: row.id, username: row.username, passHash: row.pass_hash, createdAt: iso(row.created_at) };
  }

  async getUserByUsername(username: string): Promise<UserRow | null> {
    const row = await this.one<{ id: string; username: string; pass_hash: string; created_at: Date }>(
      'SELECT id, username, pass_hash, created_at FROM users WHERE username = $1',
      [username],
    );
    return row
      ? { id: row.id, username: row.username, passHash: row.pass_hash, createdAt: iso(row.created_at) }
      : null;
  }

  async getUserById(id: string): Promise<UserRow | null> {
    const row = await this.one<{ id: string; username: string; pass_hash: string; created_at: Date }>(
      'SELECT id, username, pass_hash, created_at FROM users WHERE id = $1',
      [id],
    );
    return row
      ? { id: row.id, username: row.username, passHash: row.pass_hash, createdAt: iso(row.created_at) }
      : null;
  }

  async countUsers(): Promise<number> {
    const row = await this.one<{ n: string }>('SELECT COUNT(*) AS n FROM users');
    return Number(row?.n ?? 0);
  }

  async claimLegacyData(): Promise<number> {
    return 0; // Postgres only ever existed after accounts did.
  }

  // ---- attempts ----

  async insertAttempt(
    userId: string,
    a: { problemId: string; round: number; graphJson: string; scoreJson: string; overall: number; twistText: string | null },
  ): Promise<number> {
    const row = await this.one<{ id: string }>(
      `INSERT INTO attempts (user_id, problem_id, round, graph_json, score_json, overall, twist_text)
       VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id`,
      [userId, a.problemId, a.round, a.graphJson, a.scoreJson, a.overall, a.twistText],
    );
    return Number(row?.id ?? 0);
  }

  async listAttempts(userId: string, problemId?: string, limit = 100): Promise<AttemptRow[]> {
    const rows = problemId
      ? await this.q<RawAttempt>(
          `SELECT ${ATTEMPT_COLS} FROM attempts WHERE user_id = $1 AND problem_id = $2 ORDER BY id DESC LIMIT $3`,
          [userId, problemId, limit],
        )
      : await this.q<RawAttempt>(
          `SELECT ${ATTEMPT_COLS} FROM attempts WHERE user_id = $1 ORDER BY id DESC LIMIT $2`,
          [userId, limit],
        );
    return rows.map(toAttempt);
  }

  async getAttempt(userId: string, id: number): Promise<AttemptRow | null> {
    const row = await this.one<RawAttempt>(
      `SELECT ${ATTEMPT_COLS} FROM attempts WHERE user_id = $1 AND id = $2`,
      [userId, id],
    );
    return row ? toAttempt(row) : null;
  }

  async latestAttemptGraph(userId: string, problemId: string): Promise<string | null> {
    const row = await this.one<{ graph_json: string }>(
      'SELECT graph_json FROM attempts WHERE user_id = $1 AND problem_id = $2 ORDER BY id DESC LIMIT 1',
      [userId, problemId],
    );
    return row ? row.graph_json : null;
  }

  // ---- mastery ----

  async upsertMastery(userId: string, concept: string, score: number): Promise<void> {
    const clamped = Math.max(0, Math.min(1, score));
    // The EMA is computed in SQL so a concurrent second grading cannot read a
    // stale score and overwrite the first one's update.
    await this.q(
      `INSERT INTO mastery (user_id, concept, ema_score, attempts, last_seen)
       VALUES ($1, $2, $3, 1, now())
       ON CONFLICT (user_id, concept) DO UPDATE
         SET ema_score = (1 - $4::double precision) * mastery.ema_score + $4::double precision * $3::double precision,
             attempts = mastery.attempts + 1,
             last_seen = now()`,
      [userId, concept, clamped, MASTERY_ALPHA],
    );
  }

  async listMastery(userId: string): Promise<MasteryRow[]> {
    const rows = await this.q<{
      concept: string;
      ema_score: number;
      attempts: number;
      last_seen: Date | null;
    }>('SELECT concept, ema_score, attempts, last_seen FROM mastery WHERE user_id = $1', [userId]);
    return rows.map((r) => ({
      concept: r.concept,
      emaScore: Number(r.ema_score),
      attempts: Number(r.attempts),
      lastSeen: r.last_seen ? iso(r.last_seen) : null,
    }));
  }

  async reviewQueue(userId: string): Promise<ReviewQueueRow[]> {
    const rows = await this.q<{
      concept: string;
      ema_score: number;
      attempts: number;
      last_seen: Date | null;
      days_since: number;
    }>(
      `SELECT concept, ema_score, attempts, last_seen,
              EXTRACT(EPOCH FROM (now() - last_seen)) / 86400.0 AS days_since
       FROM mastery WHERE user_id = $1 AND last_seen IS NOT NULL`,
      [userId],
    );
    return rows.map((r) => ({
      concept: r.concept,
      emaScore: Number(r.ema_score),
      attempts: Number(r.attempts),
      lastSeen: r.last_seen ? iso(r.last_seen) : null,
      daysSince: Number(r.days_since),
    }));
  }

  async statsAgg(userId: string): Promise<StatsAgg> {
    const row = await this.one<{ n: string; avg: string | null }>(
      'SELECT COUNT(*) AS n, AVG(overall) AS avg FROM attempts WHERE user_id = $1',
      [userId],
    );
    return {
      attempts: Number(row?.n ?? 0),
      avgOverall: row?.avg === null || row?.avg === undefined ? null : Number(row.avg),
    };
  }

  async statsTrend(userId: string, limit: number): Promise<{ date: string; overall: number }[]> {
    const rows = await this.q<{ date: string; overall: number }>(
      `SELECT to_char(created_at, 'YYYY-MM-DD') AS date, overall
       FROM attempts WHERE user_id = $1 ORDER BY id DESC LIMIT $2`,
      [userId, limit],
    );
    return rows.map((r) => ({ date: r.date, overall: Number(r.overall) }));
  }

  async statsDays(userId: string): Promise<string[]> {
    const rows = await this.q<{ d: string }>(
      `SELECT DISTINCT to_char(created_at, 'YYYY-MM-DD') AS d FROM attempts WHERE user_id = $1 ORDER BY d DESC`,
      [userId],
    );
    return rows.map((r) => r.d);
  }

  // ---- custom problems ----

  async insertCustomProblem(userId: string, id: string, json: string): Promise<void> {
    await this.q(
      `INSERT INTO problems_custom (user_id, id, json) VALUES ($1, $2, $3)
       ON CONFLICT (user_id, id) DO UPDATE SET json = excluded.json`,
      [userId, id, json],
    );
  }

  async listCustomProblems(userId: string): Promise<string[]> {
    const rows = await this.q<{ json: string }>(
      'SELECT json FROM problems_custom WHERE user_id = $1 ORDER BY created_at DESC',
      [userId],
    );
    return rows.map((r) => r.json);
  }

  async deleteCustomProblem(userId: string, id: string): Promise<void> {
    await this.q('DELETE FROM problems_custom WHERE user_id = $1 AND id = $2', [userId, id]);
  }

  // ---- settings ----

  async getSetting(userId: string, key: string): Promise<string | null> {
    const row = await this.one<{ value: string }>(
      'SELECT value FROM settings WHERE user_id = $1 AND key = $2',
      [userId, key],
    );
    return row ? row.value : null;
  }

  async setSetting(userId: string, key: string, value: string): Promise<void> {
    await this.q(
      `INSERT INTO settings (user_id, key, value) VALUES ($1, $2, $3)
       ON CONFLICT (user_id, key) DO UPDATE SET value = excluded.value`,
      [userId, key, value],
    );
  }

  // ---- designs ----

  async getDesign(userId: string, problemId: string): Promise<{ graphJson: string; updatedAt: string } | null> {
    const row = await this.one<{ graph_json: string; updated_at: Date }>(
      'SELECT graph_json, updated_at FROM designs WHERE user_id = $1 AND problem_id = $2',
      [userId, problemId],
    );
    return row ? { graphJson: row.graph_json, updatedAt: iso(row.updated_at) } : null;
  }

  async putDesign(userId: string, problemId: string, graphJson: string): Promise<void> {
    await this.q(
      `INSERT INTO designs (user_id, problem_id, graph_json, updated_at) VALUES ($1, $2, $3, now())
       ON CONFLICT (user_id, problem_id) DO UPDATE SET graph_json = excluded.graph_json, updated_at = now()`,
      [userId, problemId, graphJson],
    );
  }

  async listDesignActivity(
    userId: string,
    limit = 40,
  ): Promise<{ problemId: string; updatedAt: string }[]> {
    const rows = await this.q<{ problem_id: string; updated_at: Date | string }>(
      `SELECT problem_id, updated_at FROM designs WHERE user_id = $1
       ORDER BY updated_at DESC LIMIT $2`,
      [userId, limit],
    );
    return rows.map((r) => ({ problemId: r.problem_id, updatedAt: iso(r.updated_at) }));
  }

  // ---- notes ----

  // ---- API tokens ----

  async createApiToken(
    userId: string,
    token: { id: string; name: string; hash: string },
  ): Promise<ApiTokenRow> {
    const row = await this.one<RawApiToken>(
      `INSERT INTO api_tokens (id, user_id, name, hash) VALUES ($1, $2, $3, $4)
       RETURNING id, name, created_at, last_used_at`,
      [token.id, userId, token.name, token.hash],
    );
    if (!row) throw new Error('Insert returned no token row');
    return toApiToken(row);
  }

  async listApiTokens(userId: string): Promise<ApiTokenRow[]> {
    const rows = await this.q<RawApiToken>(
      `SELECT id, name, created_at, last_used_at FROM api_tokens
       WHERE user_id = $1 ORDER BY created_at DESC, id`,
      [userId],
    );
    return rows.map(toApiToken);
  }

  async findApiToken(
    id: string,
  ): Promise<{ id: string; userId: string; hash: string; lastUsedAt: string } | null> {
    const row = await this.one<{ id: string; user_id: string; hash: string; last_used_at: Date | string | null }>(
      'SELECT id, user_id, hash, last_used_at FROM api_tokens WHERE id = $1',
      [id],
    );
    if (!row) return null;
    return { id: row.id, userId: row.user_id, hash: row.hash, lastUsedAt: iso(row.last_used_at) };
  }

  async touchApiToken(id: string): Promise<void> {
    await this.q('UPDATE api_tokens SET last_used_at = now() WHERE id = $1', [id]);
  }

  async deleteApiToken(userId: string, id: string): Promise<boolean> {
    const rows = await this.q<{ id: string }>(
      'DELETE FROM api_tokens WHERE id = $1 AND user_id = $2 RETURNING id',
      [id, userId],
    );
    return rows.length > 0;
  }

  async listNotes(userId: string, scope: NoteScope, scopeId: string): Promise<NoteRow[]> {
    const rows = await this.q<RawNote>(
      `SELECT ${NOTE_COLS} FROM notes WHERE user_id = $1 AND scope = $2 AND scope_id = $3
       ORDER BY position, created_at DESC, id`,
      [userId, scope, scopeId],
    );
    return rows.map(toNote);
  }

  async listAllNotes(userId: string): Promise<NoteRow[]> {
    // Recency, not position: `position` is manual order within one sheet, and
    // comparing one sheet's ordering against another's would mean nothing.
    const rows = await this.q<RawNote>(
      `SELECT ${NOTE_COLS} FROM notes WHERE user_id = $1 ORDER BY updated_at DESC, id`,
      [userId],
    );
    return rows.map(toNote);
  }

  async createNote(
    userId: string,
    note: { scope: NoteScope; scopeId: string; title: string; body: string },
  ): Promise<NoteRow> {
    // New notes go to the top: the one just written is the one being worked on.
    const row = await this.one<RawNote>(
      `INSERT INTO notes (id, user_id, scope, scope_id, title, body, position)
       VALUES (gen_random_uuid(), $1, $2, $3, $4, $5,
               (SELECT COALESCE(MIN(position), 0) - 1 FROM notes
                WHERE user_id = $1 AND scope = $2 AND scope_id = $3))
       RETURNING ${NOTE_COLS}`,
      [userId, note.scope, note.scopeId, note.title, note.body],
    );
    if (!row) throw new Error('Insert returned no note row');
    return toNote(row);
  }

  async updateNote(
    userId: string,
    id: string,
    patch: { title?: string; body?: string; position?: number },
  ): Promise<NoteRow | null> {
    // COALESCE over nulls rather than a built-up SET list: one statement, and the
    // pooler never sees a query shape it has not seen before.
    const row = await this.one<RawNote>(
      `UPDATE notes SET
         title = COALESCE($3, title),
         body = COALESCE($4, body),
         position = COALESCE($5, position),
         updated_at = now()
       WHERE id = $1 AND user_id = $2
       RETURNING ${NOTE_COLS}`,
      [id, userId, patch.title ?? null, patch.body ?? null, patch.position ?? null],
    );
    return row ? toNote(row) : null;
  }

  async deleteNote(userId: string, id: string): Promise<void> {
    await this.q('DELETE FROM notes WHERE id = $1 AND user_id = $2', [id, userId]);
  }

  // ---- coaching conversation ----

  async getChat(userId: string, problemId: string): Promise<string | null> {
    const row = await this.one<{ turns_json: string }>(
      'SELECT turns_json FROM chats WHERE user_id = $1 AND problem_id = $2',
      [userId, problemId],
    );
    return row ? row.turns_json : null;
  }

  async putChat(userId: string, problemId: string, turnsJson: string): Promise<void> {
    await this.q(
      `INSERT INTO chats (user_id, problem_id, turns_json, updated_at) VALUES ($1, $2, $3, now())
       ON CONFLICT (user_id, problem_id) DO UPDATE SET turns_json = excluded.turns_json, updated_at = now()`,
      [userId, problemId, turnsJson],
    );
  }

  async deleteChat(userId: string, problemId: string): Promise<void> {
    await this.q('DELETE FROM chats WHERE user_id = $1 AND problem_id = $2', [userId, problemId]);
  }

  // ---- projects and their canvases ----

  async createProject(userId: string, name: string, summary: string): Promise<ProjectRow> {
    const row = await this.one<RawProject>(
      `INSERT INTO projects (id, user_id, name, summary) VALUES (gen_random_uuid(), $1, $2, $3)
       RETURNING id, name, summary, created_at, updated_at`,
      [userId, name, summary],
    );
    if (!row) throw new Error('Insert returned no project row');
    return toProject(row);
  }

  async listProjects(userId: string): Promise<(ProjectRow & { canvasCount: number })[]> {
    const rows = await this.q<RawProject>(
      `SELECT p.id, p.name, p.summary, p.created_at, p.updated_at,
              (SELECT COUNT(*) FROM project_canvases c WHERE c.project_id = p.id) AS canvas_count
       FROM projects p WHERE p.user_id = $1 ORDER BY p.updated_at DESC, p.created_at DESC, p.id`,
      [userId],
    );
    return rows.map((r) => ({ ...toProject(r), canvasCount: Number(r.canvas_count ?? 0) }));
  }

  async getProject(userId: string, id: string): Promise<ProjectRow | null> {
    const row = await this.one<RawProject>(
      'SELECT id, name, summary, created_at, updated_at FROM projects WHERE user_id = $1 AND id = $2',
      [userId, id],
    );
    return row ? toProject(row) : null;
  }

  async updateProject(
    userId: string,
    id: string,
    patch: { name?: string; summary?: string },
  ): Promise<void> {
    // COALESCE keeps the untouched column rather than needing a query per field.
    await this.q(
      `UPDATE projects SET name = COALESCE($3, name), summary = COALESCE($4, summary),
              updated_at = now()
       WHERE user_id = $1 AND id = $2`,
      [userId, id, patch.name ?? null, patch.summary ?? null],
    );
  }

  async deleteProject(userId: string, id: string): Promise<void> {
    // The foreign key cascades, but being explicit costs nothing and does not
    // depend on the constraint having been created the way this code assumes.
    await this.q('DELETE FROM project_canvases WHERE user_id = $1 AND project_id = $2', [userId, id]);
    await this.q('DELETE FROM projects WHERE user_id = $1 AND id = $2', [userId, id]);
  }

  async createCanvas(userId: string, projectId: string, name: string, note: string): Promise<CanvasRow> {
    const row = await this.one<RawCanvas>(
      `INSERT INTO project_canvases (id, project_id, user_id, name, note, graph_json, position)
       VALUES (gen_random_uuid(), $1, $2, $3, $4, '{}',
               (SELECT COALESCE(MAX(position), -1) + 1 FROM project_canvases WHERE project_id = $1))
       RETURNING id, project_id, name, note, graph_json, position, updated_at`,
      [projectId, userId, name, note],
    );
    if (!row) throw new Error('Insert returned no canvas row');
    await this.touchProject(userId, projectId);
    return toCanvas(row);
  }

  async listCanvases(userId: string, projectId: string): Promise<CanvasRow[]> {
    const rows = await this.q<RawCanvas>(
      `SELECT id, project_id, name, note, graph_json, position, updated_at
       FROM project_canvases WHERE user_id = $1 AND project_id = $2 ORDER BY position, updated_at`,
      [userId, projectId],
    );
    return rows.map(toCanvas);
  }

  async getCanvas(userId: string, id: string): Promise<CanvasRow | null> {
    const row = await this.one<RawCanvas>(
      `SELECT id, project_id, name, note, graph_json, position, updated_at
       FROM project_canvases WHERE user_id = $1 AND id = $2`,
      [userId, id],
    );
    return row ? toCanvas(row) : null;
  }

  async updateCanvas(
    userId: string,
    id: string,
    patch: { name?: string; note?: string; graphJson?: string; position?: number },
  ): Promise<void> {
    const row = await this.one<{ project_id: string }>(
      `UPDATE project_canvases
       SET name = COALESCE($3, name), note = COALESCE($4, note),
           graph_json = COALESCE($5, graph_json), position = COALESCE($6, position),
           updated_at = now()
       WHERE user_id = $1 AND id = $2
       RETURNING project_id`,
      [userId, id, patch.name ?? null, patch.note ?? null, patch.graphJson ?? null, patch.position ?? null],
    );
    if (row) await this.touchProject(userId, row.project_id);
  }

  async deleteCanvas(userId: string, id: string): Promise<void> {
    await this.q('DELETE FROM project_canvases WHERE user_id = $1 AND id = $2', [userId, id]);
  }

  /** A project's timestamp reflects the newest work in it, not when it was named. */
  private async touchProject(userId: string, projectId: string): Promise<void> {
    await this.q('UPDATE projects SET updated_at = now() WHERE user_id = $1 AND id = $2', [
      userId,
      projectId,
    ]);
  }

  // ---- reference designs ----

  async getReference(problemId: string): Promise<string | null> {
    const row = await this.one<{ graph_json: string }>(
      'SELECT graph_json FROM reference_designs WHERE problem_id = $1',
      [problemId],
    );
    return row ? row.graph_json : null;
  }

  async putReference(problemId: string, graphJson: string): Promise<void> {
    await this.q(
      `INSERT INTO reference_designs (problem_id, graph_json) VALUES ($1, $2)
       ON CONFLICT (problem_id) DO UPDATE SET graph_json = excluded.graph_json, created_at = now()`,
      [problemId, graphJson],
    );
  }

  // ---- llm cache ----

  async cacheGet(key: string): Promise<string | null> {
    const row = await this.one<{ response: string }>('SELECT response FROM llm_cache WHERE key = $1', [key]);
    return row ? row.response : null;
  }

  async cachePut(key: string, response: string): Promise<void> {
    await this.q(
      `INSERT INTO llm_cache (key, response) VALUES ($1, $2)
       ON CONFLICT (key) DO UPDATE SET response = excluded.response, created_at = now()`,
      [key, response],
    );
  }

  async cacheDelete(key: string): Promise<void> {
    await this.q('DELETE FROM llm_cache WHERE key = $1', [key]);
  }
}
