// Refresh the vendored copy of the System Design Primer.
//
//   node scripts/vendor-primer.mjs
//
// Fetches the primer's README, keeps it as the source of truth in the repo, and
// generates a TypeScript module holding the same text.
//
// Why generate a module rather than read the .md at runtime: the server is bundled
// for a serverless host, and a file sitting next to a source file is not guaranteed
// to travel with it. A module is. The .md is kept anyway, because a generated file
// with no visible origin is a file nobody dares update.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE = 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md';
const LICENSE = 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/LICENSE.txt';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'server', 'src', 'reference', 'primer');
mkdirSync(out, { recursive: true });

const get = async (url) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  return res.text();
};

const markdown = await get(SOURCE);
writeFileSync(join(out, 'README.md'), markdown, 'utf8');
writeFileSync(join(out, 'LICENSE-CC-BY-4.0.txt'), await get(LICENSE), 'utf8');

// A template literal is the only form that survives 110KB of markdown without
// turning every newline into an escape sequence, so exactly three characters need
// escaping: the backtick, the backslash, and the `${` that would start a
// substitution.
const escaped = markdown
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

writeFileSync(
  join(out, 'text.ts'),
  `// GENERATED by scripts/vendor-primer.mjs — do not edit.
//
// The System Design Primer by Donne Martin, licensed CC BY 4.0.
// https://github.com/donnemartin/system-design-primer
//
// Vendored rather than fetched at runtime: this has to work offline, and a
// reference that sometimes fails to load is a reference nobody trusts. Refresh it
// with \`node scripts/vendor-primer.mjs\`.

export const PRIMER_MARKDOWN = \`${escaped}\`;
`,
  'utf8',
);

console.log(`vendored ${markdown.length} characters into server/src/reference/primer/text.ts`);
